const countryNamesByCode: Record<string, string> = {
  AFG: 'Afghanistan',
  AGO: 'Angola',
  ALA: 'Åland Islands',
  ALB: 'Albania',
  AND: 'Andorra',
  ARE: 'United Arab Emirates',
  ARG: 'Argentina',
  ARM: 'Armenia',
  ASM: 'American Samoa',
  ATA: 'Antarctica',
  ATF: 'French Southern Territories',
  ATG: 'Antigua and Barbuda',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',
  BDI: 'Burundi',
  BEL: 'Belgium',
  BEN: 'Benin',
  BES: 'Caribbean Netherlands',
  BFA: 'Burkina Faso',
  BGD: 'Bangladesh',
  BGR: 'Bulgaria',
  BHR: 'Bahrain',
  BHS: 'Bahamas',
  BIH: 'Bosnia and Herzegovina',
  BLR: 'Belarus',
  BLZ: 'Belize',
  BOL: 'Bolivia',
  BRA: 'Brazil',
  BRB: 'Barbados',
  BRN: 'Brunei',
  BTN: 'Bhutan',
  BWA: 'Botswana',
  CAF: 'Central African Republic',
  CAN: 'Canada',
  CHE: 'Switzerland',
  CHL: 'Chile',
  CHN: 'China',
  CIV: "Côte d'Ivoire",
  CMR: 'Cameroon',
  COD: 'Democratic Republic of the Congo',
  COG: 'Republic of the Congo',
  COL: 'Colombia',
  COM: 'Comoros',
  CPV: 'Cabo Verde',
  CRI: 'Costa Rica',
  CUB: 'Cuba',
  CUW: 'Curaçao',
  CXR: 'Christmas Island',
  CYP: 'Cyprus',
  CZE: 'Czechia',
  DEU: 'Germany',
  DJI: 'Djibouti',
  DMA: 'Dominica',
  DNK: 'Denmark',
  DOM: 'Dominican Republic',
  DZA: 'Algeria',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  ERI: 'Eritrea',
  ESH: 'Western Sahara',
  ESP: 'Spain',
  EST: 'Estonia',
  ETH: 'Ethiopia',
  FIN: 'Finland',
  FJI: 'Fiji',
  FLK: 'Falkland Islands',
  FRA: 'France',
  FRO: 'Faroe Islands',
  FSM: 'Micronesia',
  GAB: 'Gabon',
  GBR: 'United Kingdom',
  GEO: 'Georgia',
  GHA: 'Ghana',
  GIN: 'Guinea',
  GLP: 'Guadeloupe',
  GMB: 'Gambia',
  GNB: 'Guinea-Bissau',
  GNQ: 'Equatorial Guinea',
  GRC: 'Greece',
  GRD: 'Grenada',
  GRL: 'Greenland',
  GTM: 'Guatemala',
  GUM: 'Guam',
  GUY: 'Guyana',
  HKG: 'Hong Kong',
  HMD: 'Heard Island and McDonald Islands',
  HND: 'Honduras',
  HRV: 'Croatia',
  HTI: 'Haiti',
  HUN: 'Hungary',
  IDN: 'Indonesia',
  IMN: 'Isle of Man',
  IND: 'India',
  IRL: 'Ireland',
  IRN: 'Iran',
  IRQ: 'Iraq',
  ISL: 'Iceland',
  ISR: 'Israel',
  ITA: 'Italy',
  JAM: 'Jamaica',
  JOR: 'Jordan',
  JPN: 'Japan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KGZ: 'Kyrgyzstan',
  KHM: 'Cambodia',
  KIR: 'Kiribati',
  KOR: 'South Korea',
  KWT: 'Kuwait',
  LAO: 'Laos',
  LBN: 'Lebanon',
  LBR: 'Liberia',
  LBY: 'Libya',
  LCA: 'Saint Lucia',
  LIE: 'Liechtenstein',
  LKA: 'Sri Lanka',
  LSO: 'Lesotho',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  LVA: 'Latvia',
  MAF: 'Saint Martin',
  MAR: 'Morocco',
  MDA: 'Moldova',
  MDG: 'Madagascar',
  MEX: 'Mexico',
  MHL: 'Marshall Islands',
  MKD: 'North Macedonia',
  MLI: 'Mali',
  MLT: 'Malta',
  MMR: 'Myanmar',
  MNE: 'Montenegro',
  MNG: 'Mongolia',
  MNP: 'Northern Mariana Islands',
  MOZ: 'Mozambique',
  MRT: 'Mauritania',
  MTQ: 'Martinique',
  MUS: 'Mauritius',
  MWI: 'Malawi',
  MYS: 'Malaysia',
  MYT: 'Mayotte',
  NAM: 'Namibia',
  NCL: 'New Caledonia',
  NER: 'Niger',
  NGA: 'Nigeria',
  NIC: 'Nicaragua',
  NIU: 'Niue',
  NLD: 'Netherlands',
  NOR: 'Norway',
  NPL: 'Nepal',
  NZL: 'New Zealand',
  OMN: 'Oman',
  PAK: 'Pakistan',
  PAN: 'Panama',
  PER: 'Peru',
  PHL: 'Philippines',
  PLW: 'Palau',
  PNG: 'Papua New Guinea',
  POL: 'Poland',
  PRI: 'Puerto Rico',
  PRK: 'North Korea',
  PRT: 'Portugal',
  PRY: 'Paraguay',
  PSE: 'Palestine',
  PYF: 'French Polynesia',
  QAT: 'Qatar',
  REU: 'Réunion',
  ROU: 'Romania',
  RUS: 'Russia',
  RWA: 'Rwanda',
  SAU: 'Saudi Arabia',
  SDN: 'Sudan',
  SEN: 'Senegal',
  SGP: 'Singapore',
  SGS: 'South Georgia and South Sandwich Islands',
  SJM: 'Svalbard and Jan Mayen',
  SLB: 'Solomon Islands',
  SLE: 'Sierra Leone',
  SLV: 'El Salvador',
  SOM: 'Somalia',
  SRB: 'Serbia',
  SSD: 'South Sudan',
  STP: 'São Tomé and Príncipe',
  SUR: 'Suriname',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SWE: 'Sweden',
  SWZ: 'Eswatini',
  SXM: 'Sint Maarten',
  SYC: 'Seychelles',
  SYR: 'Syria',
  TCA: 'Turks and Caicos Islands',
  TCD: 'Chad',
  TGO: 'Togo',
  THA: 'Thailand',
  TJK: 'Tajikistan',
  TKM: 'Turkmenistan',
  TLS: 'Timor-Leste',
  TON: 'Tonga',
  TTO: 'Trinidad and Tobago',
  TUN: 'Tunisia',
  TUR: 'Türkiye',
  TWN: 'Taiwan',
  TZA: 'Tanzania',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  URY: 'Uruguay',
  USA: 'United States',
  UZB: 'Uzbekistan',
  VCT: 'Saint Vincent and the Grenadines',
  VEN: 'Venezuela',
  VNM: 'Vietnam',
  VUT: 'Vanuatu',
  WSM: 'Samoa',
  XCR: 'Crimea',
  XKX: 'Kosovo',
  XWS: 'Western Sahara',
  YEM: 'Yemen',
  ZAF: 'South Africa',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe',
}

export const COUNTRY_COUNT = Object.keys(countryNamesByCode).length

const countryFlagCodeByA3 = new Map(
  'AFG=AF,AGO=AO,ALA=AX,ALB=AL,AND=AD,ARE=AE,ARG=AR,ARM=AM,ASM=AS,ATA=AQ,ATF=TF,ATG=AG,AUS=AU,AUT=AT,AZE=AZ,BDI=BI,BEL=BE,BEN=BJ,BES=BQ,BFA=BF,BGD=BD,BGR=BG,BHR=BH,BHS=BS,BIH=BA,BLR=BY,BLZ=BZ,BOL=BO,BRA=BR,BRB=BB,BRN=BN,BTN=BT,BWA=BW,CAF=CF,CAN=CA,CHE=CH,CHL=CL,CHN=CN,CIV=CI,CMR=CM,COD=CD,COG=CG,COL=CO,COM=KM,CPV=CV,CRI=CR,CUB=CU,CUW=CW,CXR=CX,CYP=CY,CZE=CZ,DEU=DE,DJI=DJ,DMA=DM,DNK=DK,DOM=DO,DZA=DZ,ECU=EC,EGY=EG,ERI=ER,ESH=EH,ESP=ES,EST=EE,ETH=ET,FIN=FI,FJI=FJ,FLK=FK,FRA=FR,FRO=FO,FSM=FM,GAB=GA,GBR=GB,GEO=GE,GHA=GH,GIN=GN,GLP=GP,GMB=GM,GNB=GW,GNQ=GQ,GRC=GR,GRD=GD,GRL=GL,GTM=GT,GUM=GU,GUY=GY,HKG=HK,HMD=HM,HND=HN,HRV=HR,HTI=HT,HUN=HU,IDN=ID,IMN=IM,IND=IN,IRL=IE,IRN=IR,IRQ=IQ,ISL=IS,ISR=IL,ITA=IT,JAM=JM,JOR=JO,JPN=JP,KAZ=KZ,KEN=KE,KGZ=KG,KHM=KH,KIR=KI,KOR=KR,KWT=KW,LAO=LA,LBN=LB,LBR=LR,LBY=LY,LCA=LC,LIE=LI,LKA=LK,LSO=LS,LTU=LT,LUX=LU,LVA=LV,MAF=MF,MAR=MA,MDA=MD,MDG=MG,MEX=MX,MHL=MH,MKD=MK,MLI=ML,MLT=MT,MMR=MM,MNE=ME,MNG=MN,MNP=MP,MOZ=MZ,MRT=MR,MTQ=MQ,MUS=MU,MWI=MW,MYS=MY,MYT=YT,NAM=NA,NCL=NC,NER=NE,NGA=NG,NIC=NI,NIU=NU,NLD=NL,NOR=NO,NPL=NP,NZL=NZ,OMN=OM,PAK=PK,PAN=PA,PER=PE,PHL=PH,PLW=PW,PNG=PG,POL=PL,PRI=PR,PRK=KP,PRT=PT,PRY=PY,PSE=PS,PYF=PF,QAT=QA,REU=RE,ROU=RO,RUS=RU,RWA=RW,SAU=SA,SDN=SD,SEN=SN,SGP=SG,SGS=GS,SJM=SJ,SLB=SB,SLE=SL,SLV=SV,SOM=SO,SRB=RS,SSD=SS,STP=ST,SUR=SR,SVK=SK,SVN=SI,SWE=SE,SWZ=SZ,SXM=SX,SYC=SC,SYR=SY,TCA=TC,TCD=TD,TGO=TG,THA=TH,TJK=TJ,TKM=TM,TLS=TL,TON=TO,TTO=TT,TUN=TN,TUR=TR,TWN=TW,TZA=TZ,UGA=UG,UKR=UA,URY=UY,USA=US,UZB=UZ,VCT=VC,VEN=VE,VNM=VN,VUT=VU,WSM=WS,XKX=XK,XWS=EH,YEM=YE,ZAF=ZA,ZMB=ZM,ZWE=ZW'
    .split(',')
    .map((entry) => entry.split('=') as [string, string]),
)

// Sterna's map contains two non-standard A3 identifiers whose matching
// regional-indicator flags are nevertheless available. Crimea deliberately
// keeps the neutral fallback because it has no ISO 3166 country flag.
export function getCountryFlagCode(countryCode?: string | null): string | null {
  const normalizedCode = countryCode?.trim().toUpperCase()
  const alpha2 = normalizedCode
    ? countryFlagCodeByA3.get(normalizedCode)
    : undefined

  if (!alpha2) return null
  return alpha2.toLowerCase()
}

/**
 * Country codes come from PostGIS now (issue #59 / ADR-005 —
 * DiscoveriesService resolves them at write time), so this file is just the
 * A3 -> display name lookup. The old client-side point-in-polygon detection
 * this used to also provide (findCountryCodeForPoint, checked against
 * countries.geo.json in the browser) is gone: it was imprecise near
 * coastlines and is fully superseded by the backend's ST_Contains lookup.
 */
export function getCountryName(countryCode?: string | null): string | null {
  const normalizedCode = countryCode?.trim().toUpperCase()

  if (!normalizedCode || normalizedCode === 'UNK') {
    return null
  }

  return countryNamesByCode[normalizedCode] ?? null
}
